version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/ruby-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
