FROM ruby:3.3-alpine
RUN apk add --no-cache \
    build-base \
    sqlite-dev \
    postgresql-dev \
    tzdata \
    yaml-dev

WORKDIR /app
COPY Gemfile Gemfile.lock* ./
RUN bundle install

EXPOSE 8080
CMD ["bundle", "exec", "rerun", "--", "ruby", "app.rb", "-o", "0.0.0.0", "-p", "8080"]
