# frozen_string_literal: true

source 'https://rubygems.org'
gem 'bcrypt'
gem 'dotenv'
gem 'json'
gem 'sqlite3'
gem 'puma'
gem 'rackup'
gem 'rswag-ui'
gem 'rubocop', require: false
gem 'pg'
gem 'rack-session', '>= 2.1.2'
gem 'sequel'
gem 'sinatra'
gem 'tailwindcss'

group :development do
  gem 'rerun'
end
group :test do
  gem 'rack-test'
  gem 'rspec'
end